### ISSUE TITLE
Laser makes water and bottom of its own cell invisible

### ISSUE THREAD

**Issue by josephcsible** [Lothrazar/Cyclic#994] opened 2018-11-23 01:56 UTC
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
When looking through a laser from the Laser Cell, water is invisible behind it, as is the redstone-looking bottom of the Laser Cell itself. The bug happens regardless of the laser's settings, but is most noticeable when the alpha transparency is zero or very close to zero.
![2018-11-22_20 53 24](https://user-images.githubusercontent.com/16061266/48926107-eb9a5580-ee98-11e8-87ee-723be49fa661.png)
![2018-11-22_20 53 39](https://user-images.githubusercontent.com/16061266/48926112-edfcaf80-ee98-11e8-8afd-8a0e1002be84.png)

**Comment by josephcsible** [comment] 2018-11-23 01:57
If it's helpful, CyclopsMC/EvilCraft#631 is a case of another mod with this problem, and has a link to a commit of how they fixed it.

**Comment by Lothrazar** [comment] 2018-12-16 16:31
Thanks for the source commit. looks like i might be able to learn something 
https://github.com/Lothrazar/Cyclic/blob/c3d732c8cbf5fe3884ec64aeda3690c39591f5de/src/main/java/com/lothrazar/cyclicmagic/util/RenderUtil.java#L95

**Comment by josephcsible** [comment] 2018-12-16 21:39
I just tested the recent changes. Now, when the alpha is 10 or less, the beam doesn't render at all. When the alpha is greater than 10, it's the same as it was before.

**Comment by Lothrazar** [comment] 2019-06-04 23:22
Update: I have no idea how to fix this at the moment, im just leaving it open since its not resolved yet.  May even be caused by forge or vanilla as ive seen other rendering issues in other mods

**Comment by Lothrazar** [comment] 2019-12-29 19:02
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.

Rendering will be redone in a new way for 1.14 +

**Closed by Lothrazar** 2019-12-29 19:02 UTC
Labels: 1.12, visual
