### ISSUE TITLE
Conveyor Belts (visuals and sneak feature)

### ISSUE THREAD

**Issue by TheSnowyChickens** [Lothrazar/Cyclic#1150] opened 2019-05-18 01:13 UTC
Minecraft Version: 1.12.2

Forge Version: 2838

Mod Version: 1.19.9

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Conveyor Belt Corners don't accept the normal walk speed, while sneaking. (all 4 types are affected)

And some visual bugs below. (all 4 types are affected)

Log file link:
My lastest log.
[2019-05-18-6.log.gz](https://github.com/Lothrazar/Cyclic/files/3193501/2019-05-18-6.log.gz)

Video/images/gifs (direct upload or link): 
![2019-05-18_03 10 13](https://user-images.githubusercontent.com/29357962/57962701-948eae00-791a-11e9-9d93-c3340ce2178e.png)

![2019-05-18_03 10 17](https://user-images.githubusercontent.com/29357962/57962705-9eb0ac80-791a-11e9-83b1-9abf22f1f40c.png)

![2019-05-18_03 10 24](https://user-images.githubusercontent.com/29357962/57962706-a1ab9d00-791a-11e9-9c9c-670081157110.png)

**Comment by Lothrazar** [comment] 2019-06-02 05:31
What exactly do you mean by the "accept" part of 
" don't accept the normal walk speed, "

**Comment by Lothrazar** [comment] 2019-06-02 05:33
When player is sneaking, the conveyors do not affect the player at all, this is by design. It allows you to walk on them without being affected

**Comment by Lothrazar** [comment] 2019-06-02 05:34
The visual issues i do sometimes see , yeah but im confused about the other part

**Comment by Lothrazar** [comment] 2019-06-02 05:44
The visual thing isnt going to get fixed in 1.12 imma be honest. maybe 113 when i redo everything

**Comment by TheSnowyChickens** [comment] 2019-06-02 12:19
Sry, I am late.

And okay and yes, my english is not the best at all. :D
But good, that you understand it at the end^^

**Comment by Lothrazar** [comment] 2019-06-02 15:47
https://minecraft.curseforge.com/projects/cyclic/files/2719060

**Closed by Lothrazar** 2019-06-02 15:47 UTC
Labels: bug: gameplay, done [indev]
