### ISSUE TITLE
Fluid Extraction cables randomly stop working

### ISSUE THREAD

**Issue by jacobcrny** [Lothrazar/Cyclic#1145] opened 2019-05-11 17:49 UTC
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.12.2-1.19.8

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
I am using fluid extraction cables to pump lava from cauldrons to geothermal generators in Sky Factory 4 and it works fine for about 30 mins - 1 hr then it just stops transferring the lava causing all of my power to run out.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment] 2019-06-02 01:39
You can right click the cable to see if its empty or full or buffered.

Main cause is just buffering and needing multiple channels, duplicate of this https://github.com/Lothrazar/Cyclic/issues/1125

Any change will fix all three not just items

**Closed by Lothrazar** 2019-06-02 01:39 UTC
Labels: bug: gameplay
