### ISSUE TITLE
Energy Transfer Node doesn't work with Mekanism 

### ISSUE THREAD

**Issue by Lyceon102** [Lothrazar/Cyclic#1156] opened 2019-05-27 09:45 UTC
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.19.8

Single Player or Server: Single Player

Modpack: Sky Factory 4 version 4.0.5

Describe problem (what you were doing; what happened; what should have happened):
The energy transfer node doesn't work with most of Mekanism machines which is very annoying. I just started Sky Factory 4 so I don't have many machines tested yet. Only the Metallurgic Infuser seems to work for me; however, the upgraded version (Basic Infusing Factory) doesn't work. The crusher also doesn't work. Also when I click the question mark below the GPS, it says "Air <mekanism:machineblock:2>", the number will change depending on the Mekanism machine.

Video/images/gifs (direct upload or link): 
Basic Infusing Factory: 
![2019-05-27_16 40 04](https://user-images.githubusercontent.com/51078738/58411339-43ab5200-809e-11e9-81c7-8efaa0cd439f.png)

Metallurgic Infuser: 
![2019-05-27_16 40 06](https://user-images.githubusercontent.com/51078738/58411340-43ab5200-809e-11e9-82f2-b0b7cdb7e074.png)

![2019-05-27_16 42 59](https://user-images.githubusercontent.com/51078738/58411545-b9afb900-809e-11e9-91a9-419f393c1e74.png)

Both machines are linked to the Energy Transfer Node using GPS

**Comment by Lothrazar** [comment] 2019-06-01 16:42
Its possible this is working as intended, if Mekanism  sometimes is strict about what side of the machine it allows, or when it can be inserted/pulled from. but ill investigate

**Comment by Lothrazar** [comment] 2019-06-02 05:58
Yep some mods like Mek are very strict about not allowing any input on any side except their one specific side, but this new feature will fix it:  

Closed as duplicate, will be in next version
https://github.com/Lothrazar/Cyclic/issues/1126

**Closed by Lothrazar** 2019-06-02 05:58 UTC
Labels: mod compat
