### ISSUE TITLE
Name Tags Drop even when config is set false

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/Cyclic#1102] opened 2019-04-12 18:55 UTC
Minecraft Version: 1.12.2

Forge Version: 2831

Mod Version: 1.19.0

Single Player or Server: Server

Describe problem (what you were doing / what happened):
Name tags from named mobs are dropping on death even when config is disabled: 

Log file (text block or link):

        # When an entity dies that is named with a tag, it drops the nametag [default: true]
        B:"Name Tag Death"=false

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment] 2019-04-13 01:58
I cannot replicate this with cyclic alone, i set    B:"Name Tag Death"=false and nothing drops, my breakpoints are not hit.  So config works when i test it so ?

Any other quark like mods that might have this feature? 


To help you test out if its another mod doing it, i made a custom build that adds the text "HEY DARKO" to end of nametag after its dropped  
![tag](https://user-images.githubusercontent.com/621529/56073196-fe80ca00-5d54-11e9-842c-4439a93cc582.gif)

**Comment by Lothrazar** [comment] 2019-04-13 01:58
https://github.com/Lothrazar/Cyclic/releases/tag/1.19.SNAPSHOT

**Comment by Lothrazar** [comment] 2019-04-18 02:23
i killed some parrots that subscribed to   darkphan  and got no nametags , so i assume it was resolved in 4.0.1 , and possibly caused by some other mod

**Closed by Lothrazar** 2019-04-18 02:23 UTC
Labels: cannot replicate
