### ISSUE TITLE
Automated User and Thermal Watering Can

### ISSUE THREAD

**Issue by ashcraven** [Lothrazar/Cyclic#1076] opened 2019-02-28 15:48 UTC
Minecraft Version: 1.12.2

Mod Version: 1.18.0

Single Player or Server: Both

Describe problem (what you were doing / what happened):
Using Thermal watering can in Automated User and it places water source block instead of watering area.

Log file (text block or link):
No error message or log to link.

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)
![2019-02-28_09 43 28](https://user-images.githubusercontent.com/48096811/53578694-bc514f80-3b3d-11e9-8c68-9d53f63b9228.png)
![2019-02-28_09 43 49](https://user-images.githubusercontent.com/48096811/53578698-beb3a980-3b3d-11e9-8d3b-c1e7d86da53e.png)
![2019-02-28_09 43 45](https://user-images.githubusercontent.com/48096811/53578705-c1160380-3b3d-11e9-9e1b-1d5b32e64c65.png)

**Comment by Lothrazar** [comment] 2019-06-05 00:34
Thanks for being so patient, fnally coming back to this now. 

 this was party working as intended since the thermal watering can works slightly different than other watering items, not only with the events it uses but it has a FluidStack capability, so the user is treating it like a bucket first.  Perhaps one of the only ways to solve this is to have a new toggle button in the GUI to turn off the fluid capability section, since if a "bucket" has placed water theres no reason to then also go into the branch of "make fake player do a clicky thing" .

That said testing in the latest version, it appears its placing water but not draining from the container.   it stays at 60,000 uB the resonant one

**Comment by Lothrazar** [comment] 2019-12-29 19:20
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.

**Closed by Lothrazar** 2019-12-29 19:20 UTC
Labels: 1.12, bug: gameplay, mod compat
