### ISSUE TITLE
[1.12.2] Performance problem

### ISSUE THREAD

**Issue by bigenergy** [Lothrazar/Cyclic#1295] opened 2020-01-31 19:41 UTC
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.12.2-1.19.19

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
Cyclic causes high loads on my server

Log file link: https://sparkprofiler.github.io/#h3gWTGMoD6

**Comment by Lothrazar** [comment] 2020-02-16 23:58
The sparkprofiler link does not work, but Yes there was a chunk update bug introduced in 1.19.19.

Rolling back to 1.19.18 avoids the issue. also will be fixed in the next update coming soon.

Caused by https://github.com/Lothrazar/Cyclic/issues/1286 , closing as duplicate

**Closed by Lothrazar** 2020-02-16 23:58 UTC
Labels: 1.12
